### ISSUE TITLE
Add mohalla level between ward and polling booth

### ISSUE THREAD

**Issue by charanjeetaap** [AamAadmiParty/cleansweep-delhi#5]
We need to figure out, how to go about this. Right now polling station is the level between ward and polling booth.

Can we have both mohalla and polling station level in the system? because both are required. but there is no direct mapping between them.

**Comment by raghavio** [comment]
We can add it but there has to be a mapping between wards -> mohallas and mohallas -> polling stations.

**Comment by charanjeetaap** [comment]
there is a mapping between ward-->mohalla, assembly-->mohalla, mohalla-->polling booth

but no mapping between mohalla-->polling station

**Comment by raghavio** [comment]
We know which polling booth belongs to which station. So that can be handled.

**Comment by charanjeetaap** [comment]
Its Done
